name: Rust

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - name: Run tests
      run: cargo test --test disk
